### ISSUE TITLE
A question about multi-sample training

### ISSUE THREAD

**Issue by QuietgraceH** [marvinquiet/Cellcano#11]
Hi,wenjing.Bother you again.When I use `Cellcano preprocess` to create a gene matrix from the data, an error is reported, the specific content is as follows.I don't know if it's a problem with the file path or something else. Can you check it out for me?thank you.

```
R[write to console]: Saving ArchRProject...

R[write to console]: ArchR logging to : ArchRLogs/ArchR-getMatrixFromProject-12b345949cca7-Date-2023-08-25_Time-11-08-57.03071.log
If there is an issue, please report to github with logFile!

R[write to console]: Error in h5checktypeOrOpenLoc(file, readonly = TRUE, fapl = NULL, native = native) : 
  Error in h5checktypeOrOpenLoc(). Cannot open file. File 'NA' does not exist.

Traceback (most recent call last):
  File "/data/houjy/anaconda3/envs/cellcano/bin/Cellcano", line 8, in <module>
    sys.exit(main())
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/Cellcano/main.py", line 107, in main
    preprocess.preprocess(args)
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/Cellcano/preprocess.py", line 156, in preprocess
    _run_ArchR(input_files, sample_names, output_dir=output_dir)
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/Cellcano/preprocess.py", line 69, in _run_ArchR
    ArchR_genescore_mat = ArchR_genescore_func(ArchR_proj, useMatrix="GeneScoreMatrix")
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 208, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/data/houjy/anaconda3/envs/cellcano/lib/python3.8/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in h5checktypeOrOpenLoc(file, readonly = TRUE, fapl = NULL, native = native) : 
  Error in h5checktypeOrOpenLoc(). Cannot open file. File 'NA' does not exist.

```

**Comment by nleroy917** [comment]
Hi @QuietgraceH I am having this problem as well, what solved it for you?
