### ISSUE TITLE
Can't install Cellcano in M1 Mac

### ISSUE THREAD

**Issue by nleroy917** [marvinquiet/Cellcano#6]
Hi! Thanks for providing this package. I really appreciate the clear documentation.

**I had an issue installing `Cellcano`:**
I can't seem to install `Cellcano` in a fresh virtual environment with python on my M1 MacBook. I first tried to install using the instructions [in the documentation](https://marvinquiet.github.io/Cellcano/#installation):

```
pip install Cellcano
```

This gives a really long, and odd stack trace:

```
pip install Cellcano
Collecting Cellcano
  Using cached Cellcano-1.0.4.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of cellcano to determine which version is compatible with other requirements. This could take a while.
  Using cached Cellcano-1.0.3.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Cellcano-1.0.2.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Cellcano-1.0.1.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Cellcano-1.0.0.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/nathanleroy/sandbox/cellcano-test/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/nathanleroy/sandbox/cellcano-test/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/nathanleroy/sandbox/cellcano-test/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/_w/yrr0qqbd52gc6jj0fnqyk8640000gn/T/pip-build-env-fhqejdy_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/_w/yrr0qqbd52gc6jj0fnqyk8640000gn/T/pip-build-env-fhqejdy_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/_w/yrr0qqbd52gc6jj0fnqyk8640000gn/T/pip-build-env-fhqejdy_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/_w/yrr0qqbd52gc6jj0fnqyk8640000gn/T/pip-build-env-fhqejdy_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'DESCRIPTION'
      [end of output]
```

It seemed to be getting stuck looking through PyPi versions... so I then cloned the repository and tried to install from source:

```
git clone https://github.com/marvinquiet/Cellcano.git
cd Cellcano
pip install .
```

This got me further but gave me a weird `FileNotFoundError` for the `rpy2` dependency:

```
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/_w/yrr0qqbd52gc6jj0fnqyk8640000gn/T/pip-install-5_qkniwu/rpy2_6697f4de8fe84bab886138ed845b2719/requirements.txt'
```

Finally, I just manually removed all pinned dependencies from `setup.py` and specified the `tensorflow-macos` requirement instead of `tensorflow`, and then everything was installed nicely. I haven't tested it fully, but I thought I'd open the issue to let you know there might be install issues on an M1.

**Comment by nleroy917** [comment]
Thanks! Everything worked great once I messed with the dependencies a bit. It was super easy using the reference data you provided - pipelines like this are very much needed!!!

For reference, these are the reqs I went with:

```python
 install_requires=[
        'tensorflow',
        'six',
        'anndata',
        'scanpy',
        'numpy',
        'h5py',
        'keras',
        'rpy2'
]
```

I just removed any pinned dependencies.
